app_name: World Chain Network
app_subtitle: Earn World Chain Token
app_download: https://play.google.com/store/apps/details?id=com.ekicisoft.worldchain&referrer=JUgFvlpuAeWRWMvWiRiuWVzN5ZI3
app_github: https://play.google.com/store/apps/details?id=com.ekicisoft.worldchain&referrer=JUgFvlpuAeWRWMvWiRiuWVzN5ZI3
app_id: 1534437697
email: mail@kruschel.dev
app_icon: /assets/icon.png
favicon: /assets/icon.png

made_by: // Made by [Miká Kruschel](https://kruschel.dev)

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

app_description: |

 World Chain Network Mining App
 Earn WorldChain Token
 1500 WorlChain Token every Referral
    
####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
